/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as UserSubmitFriendLinkRouteImport } from './routes/_user/submit-friend-link'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicPostsRouteImport } from './routes/_public/posts'
import { Route as PublicFriendLinksRouteImport } from './routes/_public/friend-links'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetLinkRouteImport } from './routes/_auth/reset-link'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminFriendLinksIndexRouteImport } from './routes/admin/friend-links/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as PublicTagsNameRouteImport } from './routes/_public/tags/$name'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as PublicAuthorUsernameRouteImport } from './routes/_public/author/$username'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmitFriendLinkRoute = UserSubmitFriendLinkRouteImport.update({
  id: '/submit-friend-link',
  path: '/submit-friend-link',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostsRoute = PublicPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFriendLinksRoute = PublicFriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetLinkRoute = AuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFriendLinksIndexRoute = AdminFriendLinksIndexRouteImport.update({
  id: '/friend-links/',
  path: '/friend-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicTagsNameRoute = PublicTagsNameRouteImport.update({
  id: '/tags/$name',
  path: '/tags/$name',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthorUsernameRoute = PublicAuthorUsernameRouteImport.update({
  id: '/author/$username',
  path: '/author/$username',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/posts': typeof PublicPostsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/search': typeof PublicSearchRoute
  '/terms': typeof PublicTermsRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/author/$username': typeof PublicAuthorUsernameRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/tags/$name': typeof PublicTagsNameRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/posts': typeof PublicPostsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/search': typeof PublicSearchRoute
  '/terms': typeof PublicTermsRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/author/$username': typeof PublicAuthorUsernameRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/tags/$name': typeof PublicTagsNameRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-link': typeof AuthResetLinkRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/friend-links': typeof PublicFriendLinksRoute
  '/_public/posts': typeof PublicPostsRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/author/$username': typeof PublicAuthorUsernameRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/_public/tags/$name': typeof PublicTagsNameRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/admin/posts'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/friend-links'
    | '/posts'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/unsubscribe'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/'
    | '/admin/'
    | '/author/$username'
    | '/post/$slug'
    | '/tags/$name'
    | '/admin/comments'
    | '/admin/friend-links'
    | '/admin/media'
    | '/admin/posts/'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/friend-links'
    | '/posts'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/unsubscribe'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/'
    | '/admin'
    | '/author/$username'
    | '/post/$slug'
    | '/tags/$name'
    | '/admin/comments'
    | '/admin/friend-links'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/admin/posts'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-link'
    | '/_auth/verify-email'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/friend-links'
    | '/_public/posts'
    | '/_public/privacy'
    | '/_public/search'
    | '/_public/terms'
    | '/_public/unsubscribe'
    | '/_user/profile'
    | '/_user/submit-friend-link'
    | '/oauth/consent'
    | '/_public/'
    | '/admin/'
    | '/_public/author/$username'
    | '/_public/post/$slug'
    | '/_public/tags/$name'
    | '/admin/comments/'
    | '/admin/friend-links/'
    | '/admin/media/'
    | '/admin/posts/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/users/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/submit-friend-link': {
      id: '/_user/submit-friend-link'
      path: '/submit-friend-link'
      fullPath: '/submit-friend-link'
      preLoaderRoute: typeof UserSubmitFriendLinkRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/friend-links': {
      id: '/_public/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof PublicFriendLinksRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-link': {
      id: '/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof AuthResetLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/friend-links/': {
      id: '/admin/friend-links/'
      path: '/friend-links'
      fullPath: '/admin/friend-links'
      preLoaderRoute: typeof AdminFriendLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/tags/$name': {
      id: '/_public/tags/$name'
      path: '/tags/$name'
      fullPath: '/tags/$name'
      preLoaderRoute: typeof PublicTagsNameRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/author/$username': {
      id: '/_public/author/$username'
      path: '/author/$username'
      fullPath: '/author/$username'
      preLoaderRoute: typeof PublicAuthorUsernameRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFriendLinksRoute: typeof PublicFriendLinksRoute
  PublicPostsRoute: typeof PublicPostsRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthorUsernameRoute: typeof PublicAuthorUsernameRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
  PublicTagsNameRoute: typeof PublicTagsNameRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFriendLinksRoute: PublicFriendLinksRoute,
  PublicPostsRoute: PublicPostsRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthorUsernameRoute: PublicAuthorUsernameRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
  PublicTagsNameRoute: PublicTagsNameRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
  UserSubmitFriendLinkRoute: typeof UserSubmitFriendLinkRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserProfileRoute: UserProfileRoute,
  UserSubmitFriendLinkRoute: UserSubmitFriendLinkRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminFriendLinksIndexRoute: typeof AdminFriendLinksIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminFriendLinksIndexRoute: AdminFriendLinksIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
